//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAddUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.DogovorKupliProdaji = new HashSet<DogovorKupliProdaji>();
            this.DogovorKupliProdaji1 = new HashSet<DogovorKupliProdaji>();
        }
    
        public int IdClient { get; set; }
        public string FirstNameClient { get; set; }
        public string SecondNameClient { get; set; }
        public string PatronymicClient { get; set; }
        public string AdressClient { get; set; }
        public string PassportSeriesClient { get; set; }
        public string PassportNumberClient { get; set; }
        public string DateIssueClient { get; set; }
        public string WhoIssuedClient { get; set; }
        public string TelephoneNumberClient { get; set; }
        public string Email { get; set; }
        public Nullable<int> DogovorOVlad { get; set; }
        public int clientType { get; set; }
    
        public virtual ClientType ClientType1 { get; set; }
        public virtual DogovorVladeniaType DogovorVladeniaType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DogovorKupliProdaji> DogovorKupliProdaji { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DogovorKupliProdaji> DogovorKupliProdaji1 { get; set; }
    }
}
