//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAddUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogovorKupliProdaji
    {
        public int idDog { get; set; }
        public int idEmployee { get; set; }
        public int idProd { get; set; }
        public int idPoc { get; set; }
        public int idRE { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual RealEstate RealEstate { get; set; }
    }
}
