//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAddUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.DogovorKupliProdaji = new HashSet<DogovorKupliProdaji>();
        }
    
        public int idEmployee { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string Patronymic { get; set; }
        public int Post { get; set; }
        public int Branch { get; set; }
        public string Adress { get; set; }
        public string TelephoneNumber { get; set; }
        public int Gender { get; set; }
    
        public virtual Branch Branch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DogovorKupliProdaji> DogovorKupliProdaji { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Post Post1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
