//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAddUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RealEstate()
        {
            this.DogovorKupliProdaji = new HashSet<DogovorKupliProdaji>();
        }
    
        public int IdRealEstateRE { get; set; }
        public int City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Apartament { get; set; }
        public int type { get; set; }
        public float ploshad { get; set; }
        public float cena { get; set; }
        public string opisanie { get; set; }
        public int komnat { get; set; }
        public int Valuta { get; set; }
    
        public virtual City City1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DogovorKupliProdaji> DogovorKupliProdaji { get; set; }
        public virtual TypeRealEstate TypeRealEstate { get; set; }
        public virtual Valuta Valuta1 { get; set; }
    }
}
