//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAddUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public int idStat { get; set; }
        public string Status1 { get; set; }
    }
}
